<a href="https://colab.research.google.com/github/amnanaseerr/pytorch-fundamentals/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

**Introduction** **to** **tensors**

Creating tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
#Get tensor bacl as python int
scalar.item()

In [ ]:
#vector
vector = torch.tensor([23, 75])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
#matrix
matrix = torch.tensor([[7, 8], [4,9]])
matrix

In [ ]:
matrix.ndim

In [ ]:
matrix[0]

In [ ]:
matrix[1]

In [ ]:
matrix.shape

In [ ]:
#tensor
TENSOR = torch.tensor([[[1,2,3,87], [4,5,2,6], [7,8,32,9], [34,776,3]]])
TENSOR

In [ ]:
TENSOR.ndim

NameError: name 'TENSOR' is not defined

In [ ]:
TENSOR.shape

NameError: name 'TENSOR' is not defined

In [ ]:
TENSOR[0]

In [ ]:
#creating random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9677, 0.7717, 0.5574, 0.3442],
        [0.0280, 0.0475, 0.2477, 0.8129],
        [0.2301, 0.1312, 0.1381, 0.3694]])

In [ ]:
random_image_size_tensor = torch.rand(size=(3,244,244))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.1148, 0.0577, 0.5448],
        [0.9839, 0.9282, 0.7018],
        [0.5651, 0.8873, 0.7954]])

In [ ]:
#zeros and ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
#torch range
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.__version__

'2.9.0+cu126'

In [ ]:
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None, device = None, requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)